## Lists

Create a list, called "Numbers". Let it contain the numbers 10, 25, 40, and 50.

In [1]:
Numbers = [ 10, 25, 40,50]

Print the element at index 2 from the list.

In [2]:
Numbers[2]

40

Print the 0th element.

In [3]:
Numbers[0]

10

Print the third-to-last element using a minus sign in the brackets.

In [66]:
Numbers[-2::]

[115, 140]

Substitute the number 10 with the number 15.

In [5]:
Numbers[0] = 15
Numbers

[15, 25, 40, 50]

Delete the number 25 from the Numbers list.

In [6]:
del Numbers[2]
Numbers

[15, 25, 50]

## Help Yourself with Methods

Append the number 100 to the Numbers list. 

In [69]:
Numbers = [15, 40, 50]

In [70]:
Numbers.append(100)
Numbers

[15, 40, 50, 100]

With the help of the "extend method", add the numbers 115 an 140 to the list. 

In [71]:
a = [115, 140]
Numbers.extend(a)
Numbers

[15, 40, 50, 100, 115, 140]

Print a statement, saying "The fourth element of the Numbers list is:" and then designate the value of the fourth element. Use a trailing comma.

In [72]:
print('The fourth element of the Numbers list is', Numbers[4])

The fourth element of the Numbers list is 115


How many elements are there in the Numbers list?

In [29]:
len(Numbers)

6

## List Slicing

In [1]:
Numbers = [15, 40, 50, 100, 115, 140]
Numbers

[15, 40, 50, 100, 115, 140]

Using list slicing, obtain the numbers 100 and 115.

In [8]:
print(Numbers[3:5])

[100, 115]


Using slicing, extract the first four elements from the list.

In [5]:
print(Numbers[::4])

[15, 115]


Using slicing, extract all the elements from the list from the 3rd position onwards.

In [78]:
print(Numbers[2:])

[50, 100, 115, 140]


Using slicing, extract the last 4 elements from the list.

In [10]:
print(Numbers[:2])

[15, 40]


Which is the position of the value 15?

In [79]:
Numbers.index(15)

0

Create a list, called "Two_Numbers". Let its elements be the values 1 and 2. Then, create a new one, named "All_Numbers", that will containt both the "Numbers" and the "Two_Numbers" lists. 

In [85]:
Two_Numbers = [1,2]
All_Numbers = [Numbers, Two_Numbers]
All_Numbers

[[15, 40, 50, 100, 115, 140], [1, 2]]

Sort all the numbers in the "Numbers" list from the largest to the smallest.

In [83]:
sorted(Numbers, reverse=True)

[140, 115, 100, 50, 40, 15]

## Tuples

Create a tuple, called "Cars", with elements "BMW", "Dodge", and "Ford". 

In [86]:
Cars=('BMW','Dodge','Ford')

Access the second element of this tuple.

In [87]:
Cars[1]

'Dodge'

Call a method that would allow you to extract the provided name and age separately. Then print the "name" and "age" values to see if you worked correctly.

In [90]:
name_age = 'Peter,24'.split(',')
name_age

['Peter', '24']

In [91]:
print('Nama',name, ' Age', age)

NameError: name 'name' is not defined

Create a function that takes as arguments the two values of a rectangle and then returns the Area and the Perimeter of the rectangle.
Call the function with arguments 2 and 10 to verify it worked correctly.

## Dictionaries

*Suggested Answers follow (usually there are multiple ways to solve a problem in Python).*

This is the menu of a close-by restaurant:

In [101]:
Menu = {'meal_1':'Spaghetti', 'meal_2':'Fries', 'meal_3':'Hamburger', 'meal_4':'Lasagna'}

What is the second meal in the list?

In [102]:
Menu['meal_2']

'Fries'

Add a new meal - "Soup".

In [106]:
Menu['meal_5'] = 'Soup'
Menu

{'meal_1': 'Spaghetti',
 'meal_2': 'Fries',
 'meal_3': 'Hamburger',
 'meal_4': 'Lasagna',
 'meal_5': 'Soup'}

Replace the Hamburger with a Cheeseburger.

In [113]:
Menu['meal_3'] = 'Cheeseburger'
Menu

{'meal_1': 'Spaghetti',
 'meal_2': 'Fries',
 'meal_3': 'Cheeseburger',
 'meal_4': 'Lasagna',
 'meal_5': 'Soup',
 ('meal_6', 'meal_7', 'meal_8'): ('Pancakes', 'Ice-cream', 'Tiramisu'),
 'meal_6': ['Pancakes', 'Ice-cream', 'Tiramisu']}

Attach the Desserts list in the form of a sixth meal.

In [111]:
Dessert = ['Pancakes', 'Ice-cream', 'Tiramisu']

In [112]:
Menu['meal_6'] = Dessert
Menu

{'meal_1': 'Spaghetti',
 'meal_2': 'Fries',
 'meal_3': 'Cheeseburger',
 'meal_4': 'Lasagna',
 'meal_5': 'Soup',
 ('meal_6', 'meal_7', 'meal_8'): ('Pancakes', 'Ice-cream', 'Tiramisu'),
 'meal_6': ['Pancakes', 'Ice-cream', 'Tiramisu']}

Create a new dictionary that contains the first five meals as keys and assign the following five values as prices (in dollars):
10, 5, 8, 12, 5. 
Start by *Price_list = {}*.

In [ ]:
Price_list={}
Price_list={'Spaghetti'}

Use the *.get()* method to check the price of the Spaghetti.